// Generated by gencpp from file reactor_control/armCmd.msg
// DO NOT EDIT!


#ifndef REACTOR_CONTROL_MESSAGE_ARMCMD_H
#define REACTOR_CONTROL_MESSAGE_ARMCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reactor_control
{
template <class ContainerAllocator>
struct armCmd_
{
  typedef armCmd_<ContainerAllocator> Type;

  armCmd_()
    : current()
    , accel()
    , vel()
    , angle()
    , msg_ctr(0)  {
      current.assign(0.0);

      accel.assign(0.0);

      vel.assign(0.0);

      angle.assign(0.0);
  }
  armCmd_(const ContainerAllocator& _alloc)
    : current()
    , accel()
    , vel()
    , angle()
    , msg_ctr(0)  {
  (void)_alloc;
      current.assign(0.0);

      accel.assign(0.0);

      vel.assign(0.0);

      angle.assign(0.0);
  }



   typedef boost::array<float, 6>  _current_type;
  _current_type current;

   typedef boost::array<float, 6>  _accel_type;
  _accel_type accel;

   typedef boost::array<float, 6>  _vel_type;
  _vel_type vel;

   typedef boost::array<float, 6>  _angle_type;
  _angle_type angle;

   typedef uint32_t _msg_ctr_type;
  _msg_ctr_type msg_ctr;





  typedef boost::shared_ptr< ::reactor_control::armCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reactor_control::armCmd_<ContainerAllocator> const> ConstPtr;

}; // struct armCmd_

typedef ::reactor_control::armCmd_<std::allocator<void> > armCmd;

typedef boost::shared_ptr< ::reactor_control::armCmd > armCmdPtr;
typedef boost::shared_ptr< ::reactor_control::armCmd const> armCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reactor_control::armCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reactor_control::armCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::reactor_control::armCmd_<ContainerAllocator1> & lhs, const ::reactor_control::armCmd_<ContainerAllocator2> & rhs)
{
  return lhs.current == rhs.current &&
    lhs.accel == rhs.accel &&
    lhs.vel == rhs.vel &&
    lhs.angle == rhs.angle &&
    lhs.msg_ctr == rhs.msg_ctr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::reactor_control::armCmd_<ContainerAllocator1> & lhs, const ::reactor_control::armCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace reactor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::reactor_control::armCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactor_control::armCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactor_control::armCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactor_control::armCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactor_control::armCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactor_control::armCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reactor_control::armCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5117dac10d971bfa5afe9a1d2ba6497a";
  }

  static const char* value(const ::reactor_control::armCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5117dac10d971bfaULL;
  static const uint64_t static_value2 = 0x5afe9a1d2ba6497aULL;
};

template<class ContainerAllocator>
struct DataType< ::reactor_control::armCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reactor_control/armCmd";
  }

  static const char* value(const ::reactor_control::armCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reactor_control::armCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] current #amp\n"
"float32[6] accel #deg/s^2\n"
"float32[6] vel #deg/s\n"
"float32[6] angle #deg\n"
"uint32 msg_ctr  # count number of messages to detect missed msgs\n"
;
  }

  static const char* value(const ::reactor_control::armCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reactor_control::armCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current);
      stream.next(m.accel);
      stream.next(m.vel);
      stream.next(m.angle);
      stream.next(m.msg_ctr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct armCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reactor_control::armCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reactor_control::armCmd_<ContainerAllocator>& v)
  {
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.current[i]);
    }
    s << indent << "accel[]" << std::endl;
    for (size_t i = 0; i < v.accel.size(); ++i)
    {
      s << indent << "  accel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.accel[i]);
    }
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vel[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
    s << indent << "msg_ctr: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.msg_ctr);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REACTOR_CONTROL_MESSAGE_ARMCMD_H
