// Generated by gencpp from file reactor_control/reactorTelemetry.msg
// DO NOT EDIT!


#ifndef REACTOR_CONTROL_MESSAGE_REACTORTELEMETRY_H
#define REACTOR_CONTROL_MESSAGE_REACTORTELEMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reactor_control
{
template <class ContainerAllocator>
struct reactorTelemetry_
{
  typedef reactorTelemetry_<ContainerAllocator> Type;

  reactorTelemetry_()
    : angle()
    , vel()
    , current()
    , startSyncTime()
    , isrTicks(0)
    , bufferHealth(0)  {
      angle.assign(0.0);

      vel.assign(0.0);

      current.assign(0.0);
  }
  reactorTelemetry_(const ContainerAllocator& _alloc)
    : angle()
    , vel()
    , current()
    , startSyncTime()
    , isrTicks(0)
    , bufferHealth(0)  {
  (void)_alloc;
      angle.assign(0.0);

      vel.assign(0.0);

      current.assign(0.0);
  }



   typedef boost::array<float, 6>  _angle_type;
  _angle_type angle;

   typedef boost::array<float, 6>  _vel_type;
  _vel_type vel;

   typedef boost::array<float, 6>  _current_type;
  _current_type current;

   typedef ros::Time _startSyncTime_type;
  _startSyncTime_type startSyncTime;

   typedef uint32_t _isrTicks_type;
  _isrTicks_type isrTicks;

   typedef uint8_t _bufferHealth_type;
  _bufferHealth_type bufferHealth;





  typedef boost::shared_ptr< ::reactor_control::reactorTelemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reactor_control::reactorTelemetry_<ContainerAllocator> const> ConstPtr;

}; // struct reactorTelemetry_

typedef ::reactor_control::reactorTelemetry_<std::allocator<void> > reactorTelemetry;

typedef boost::shared_ptr< ::reactor_control::reactorTelemetry > reactorTelemetryPtr;
typedef boost::shared_ptr< ::reactor_control::reactorTelemetry const> reactorTelemetryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reactor_control::reactorTelemetry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reactor_control::reactorTelemetry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::reactor_control::reactorTelemetry_<ContainerAllocator1> & lhs, const ::reactor_control::reactorTelemetry_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.vel == rhs.vel &&
    lhs.current == rhs.current &&
    lhs.startSyncTime == rhs.startSyncTime &&
    lhs.isrTicks == rhs.isrTicks &&
    lhs.bufferHealth == rhs.bufferHealth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::reactor_control::reactorTelemetry_<ContainerAllocator1> & lhs, const ::reactor_control::reactorTelemetry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace reactor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reactor_control::reactorTelemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reactor_control::reactorTelemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reactor_control::reactorTelemetry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbf117927605fc3413c0528694294257";
  }

  static const char* value(const ::reactor_control::reactorTelemetry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbf117927605fc34ULL;
  static const uint64_t static_value2 = 0x13c0528694294257ULL;
};

template<class ContainerAllocator>
struct DataType< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reactor_control/reactorTelemetry";
  }

  static const char* value(const ::reactor_control::reactorTelemetry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Header header \n"
"float32[6] angle # degrees\n"
"float32[6] vel # deg/s\n"
"float32[6] current # amps\n"
"#time armReadTimestamp \n"
"time startSyncTime \n"
"uint32 isrTicks # this would overflow if the robot is left on for 497 days straight at 100 hz \n"
"uint8 bufferHealth\n"
;
  }

  static const char* value(const ::reactor_control::reactorTelemetry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.vel);
      stream.next(m.current);
      stream.next(m.startSyncTime);
      stream.next(m.isrTicks);
      stream.next(m.bufferHealth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reactorTelemetry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reactor_control::reactorTelemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reactor_control::reactorTelemetry_<ContainerAllocator>& v)
  {
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle[i]);
    }
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vel[i]);
    }
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.current[i]);
    }
    s << indent << "startSyncTime: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.startSyncTime);
    s << indent << "isrTicks: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.isrTicks);
    s << indent << "bufferHealth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bufferHealth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REACTOR_CONTROL_MESSAGE_REACTORTELEMETRY_H
